[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings=["@openzeppelin/=lib/openzeppelin-contracts/"]
via_ir = true
optimizer = true
optimizer_runs = 200

# Network configurations
[rpc_endpoints]
somnia_testnet = "https://dream-rpc.somnia.network"

[etherscan]
somnia_testnet = { key = "${ETHERSCAN_API_KEY}", url = "https://testnet.somniaexplorer.com/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
